# Generated by Django 5.2.5 on 2025-10-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='notes_ru',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes_uz',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes_uz_Cyrl',
        ),
    ]
