# Generated by Django 5.2.1 on 2025-10-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('full_name_uz', models.CharField(max_length=255, null=True)),
                ('full_name_uz_Cyrl', models.CharField(max_length=255, null=True)),
                ('full_name_ru', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=32)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('source_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('source_uz_Cyrl', models.CharField(blank=True, max_length=100, null=True)),
                ('source_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('notes_uz', models.TextField(blank=True, null=True)),
                ('notes_uz_Cyrl', models.TextField(blank=True, null=True)),
                ('notes_ru', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
