# Generated by Django 5.2.5 on 2025-10-15 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='full_name_ru',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='full_name_uz',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='full_name_uz_Cyrl',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='notes_ru',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='notes_uz',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='notes_uz_Cyrl',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source_ru',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source_uz',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source_uz_Cyrl',
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='settings.doctor'),
        ),
    ]
