# Generated by Django 5.2.1 on 2025-10-14 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('services_done', models.TextField(blank=True)),
                ('services_done_uz', models.TextField(blank=True, null=True)),
                ('services_done_uz_Cyrl', models.TextField(blank=True, null=True)),
                ('services_done_ru', models.TextField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='appointments.appointment')),
            ],
        ),
    ]
