# Generated by Django 5.2.5 on 2025-10-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='services_done_ru',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='services_done_uz',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='services_done_uz_Cyrl',
        ),
    ]
