# Generated by Django 5.2.1 on 2025-10-14 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_name_uz', models.CharField(max_length=255, null=True)),
                ('doctor_name_uz_Cyrl', models.CharField(max_length=255, null=True)),
                ('doctor_name_ru', models.CharField(max_length=255, null=True)),
                ('service', models.CharField(max_length=255)),
                ('service_uz', models.CharField(max_length=255, null=True)),
                ('service_uz_Cyrl', models.CharField(max_length=255, null=True)),
                ('service_ru', models.CharField(max_length=255, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('notes_uz', models.TextField(blank=True, null=True)),
                ('notes_uz_Cyrl', models.TextField(blank=True, null=True)),
                ('notes_ru', models.TextField(blank=True, null=True)),
                ('doctor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
        ),
    ]
