# Generated by Django 5.2.5 on 2025-10-15 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_name_ru',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_name_uz',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_name_uz_Cyrl',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes_ru',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes_uz',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes_uz_Cyrl',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service_ru',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service_uz',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service_uz_Cyrl',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='settings.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='settings.treatment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
