# Generated by Django 5.2.5 on 2025-10-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address_uz',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address_uz_Cyrl',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='full_name_ru',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='full_name_uz',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='full_name_uz_Cyrl',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='notes_ru',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='notes_uz',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='notes_uz_Cyrl',
        ),
    ]
